// CODE: DOCTOR

const DOCTOR = {
  SEND   : {
    FETCH    : 'DOCTOR_SEND_FETCH',
    CREATE   : 'DOCTOR_SEND_CREATE',
    MODIFY   : 'DOCTOR_SEND_MODIFY',
    ACTIVATE : 'DOCTOR_SEND_ACTIVATE',
    REMOVE   : 'DOCTOR_SEND_REMOVE',
  },
  SAVE   : {
    REPLACE   : 'DOCTOR_SAVE_FETCH',
    ADDTOP    : 'DOCTOR_SAVE_CREATE',
    ADDBOTTOM : 'DOCTOR_SAVE_CREATE',
    MODIFY    : 'DOCTOR_SAVE_MODIFY',
    REMOVE    : 'DOCTOR_SAVE_REMOVE',
  },
  STATUS : {
    SUCCESS : 'DOCTOR_STATUS_SUCCESS',
    REQUEST : 'DOCTOR_STATUS_REQUEST',
    FAILED  : 'DOCTOR_STATUS_FAILED',
  },
}

// CODE: Appointment

const APPOINTMENT = {
  SEND   : {
    FETCH    : 'APPOINTMENT_SEND_FETCH',
    CREATE   : 'APPOINTMENT_SEND_CREATE',
    MODIFY   : 'APPOINTMENT_SEND_MODIFY',
    ACTIVATE : 'APPOINTMENT_SEND_ACTIVATE',
    REMOVE   : 'APPOINTMENT_SEND_REMOVE',
  },
  SAVE   : {
    REPLACE   : 'APPOINTMENT_SAVE_FETCH',
    ADDTOP    : 'APPOINTMENT_SAVE_CREATE_TOP',
    ADDBOTTOM : 'APPOINTMENT_SAVE_CREATE_BOTTOM',
    MODIFY    : 'APPOINTMENT_SAVE_MODIFY',
    REMOVE    : 'APPOINTMENT_SAVE_REMOVE',
  },
  STATUS : {
    SUCCESS : 'APPOINTMENT_STATUS_SUCCESS',
    REQUEST : 'APPOINTMENT_STATUS_REQUEST',
    FAILED  : 'APPOINTMENT_STATUS_FAILED',
  },
}

// CODE: User

const USER = {
  SEND   : {
    FETCH    : 'USER_SEND_FETCH',
    CREATE   : 'USER_SEND_CREATE',
    MODIFY   : 'USER_SEND_MODIFY',
    ACTIVATE : 'USER_SEND_ACTIVATE',
    REMOVE   : 'USER_SEND_REMOVE',
  },
  SAVE   : {
    REPLACE   : 'USER_SAVE_FETCH',
    ADDTOP    : 'USER_SAVE_CREATE',
    ADDBOTTOM : 'USER_SAVE_CREATE',
    MODIFY    : 'USER_SAVE_MODIFY',
    REMOVE    : 'USER_SAVE_REMOVE',
  },
  STATUS : {
    SUCCESS : 'USER_STATUS_SUCCESS',
    REQUEST : 'USER_STATUS_REQUEST',
    FAILED  : 'USER_STATUS_FAILED',
  },
}

// CODE: Temp

const REVIEW = {
  SEND   : {
    FETCH    : 'REVIEW_SEND_FETCH',
    CREATE   : 'REVIEW_SEND_CREATE',
    MODIFY   : 'REVIEW_SEND_MODIFY',
    ACTIVATE : 'REVIEW_SEND_ACTIVATE',
    REMOVE   : 'REVIEW_SEND_REMOVE',
  },
  SAVE   : {
    REPLACE   : 'REVIEW_SAVE_FETCH',
    ADDTOP    : 'REVIEW_SAVE_CREATE',
    ADDBOTTOM : 'REVIEW_SAVE_CREATE',
    MODIFY    : 'REVIEW_SAVE_MODIFY',
    REMOVE    : 'REVIEW_SAVE_REMOVE',
  },
  STATUS : {
    SUCCESS : 'REVIEW_STATUS_SUCCESS',
    REQUEST : 'REVIEW_STATUS_REQUEST',
    FAILED  : 'REVIEW_STATUS_FAILED',
  },
}

export { DOCTOR, USER, REVIEW, APPOINTMENT }
