// CODE: Temp

const DOCTOR = {
  SEND   : {
    FETCH    : 'DOCTOR_SEND_FETCH',
    CREATE   : 'DOCTOR_SEND_CREATE',
    MODIFY   : 'DOCTOR_SEND_MODIFY',
    ACTIVATE : 'DOCTOR_SEND_ACTIVATE',
    REMOVE   : 'DOCTOR_SEND_REMOVE',
  },
  SAVE   : {
    REPLACE   : 'DOCTOR_SAVE_FETCH',
    ADDTOP    : 'DOCTOR_SAVE_CREATE',
    ADDBOTTOM : 'DOCTOR_SAVE_CREATE',
    MODIFY    : 'DOCTOR_SAVE_MODIFY',
    REMOVE    : 'DOCTOR_SAVE_REMOVE',
  },
  STATUS : {
    SUCCESS : 'DOCTOR_STATUS_SUCCESS',
    REQUEST : 'DOCTOR_STATUS_REQUEST',
    FAILED  : 'DOCTOR_STATUS_FAILED',
  },
}

// CODE: Temp

const TEMP = {
  SEND   : {
    FETCH    : 'TEMP_SEND_FETCH',
    CREATE   : 'TEMP_SEND_CREATE',
    MODIFY   : 'TEMP_SEND_MODIFY',
    ACTIVATE : 'TEMP_SEND_ACTIVATE',
    REMOVE   : 'TEMP_SEND_REMOVE',
  },
  SAVE   : {
    REPLACE   : 'TEMP_SAVE_FETCH',
    ADDTOP    : 'TEMP_SAVE_CREATE',
    ADDBOTTOM : 'TEMP_SAVE_CREATE',
    MODIFY    : 'TEMP_SAVE_MODIFY',
    REMOVE    : 'TEMP_SAVE_REMOVE',
  },
  STATUS : {
    SUCCESS : 'TEMP_STATUS_SUCCESS',
    REQUEST : 'TEMP_STATUS_REQUEST',
    FAILED  : 'TEMP_STATUS_FAILED',
  },
}

export { DOCTOR, TEMP }
